// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-U3gWYtJ0WzLx208Z-SPAQgRPlQTwSD0',
    appId: '1:71391776673:web:1c761ea72c15ab384b05e0',
    messagingSenderId: '71391776673',
    projectId: 'fir-integration-app-e3c25',
    authDomain: 'fir-integration-app-e3c25.firebaseapp.com',
    storageBucket: 'fir-integration-app-e3c25.appspot.com',
    measurementId: 'G-VSK2S9FW4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfmQqPiy8lqZ4DskrWHrdta-qKfRFSE_o',
    appId: '1:71391776673:android:713448d9d872733e4b05e0',
    messagingSenderId: '71391776673',
    projectId: 'fir-integration-app-e3c25',
    storageBucket: 'fir-integration-app-e3c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdb15Irftc54jqd28KjozInoTLpcnZ1mI',
    appId: '1:71391776673:ios:d49593c0882c6c834b05e0',
    messagingSenderId: '71391776673',
    projectId: 'fir-integration-app-e3c25',
    storageBucket: 'fir-integration-app-e3c25.appspot.com',
    iosClientId: '71391776673-d5tpdsoli9guvm9st3f43ftbfqpasi35.apps.googleusercontent.com',
    iosBundleId: 'com.app.firebaseIntegrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdb15Irftc54jqd28KjozInoTLpcnZ1mI',
    appId: '1:71391776673:ios:d49593c0882c6c834b05e0',
    messagingSenderId: '71391776673',
    projectId: 'fir-integration-app-e3c25',
    storageBucket: 'fir-integration-app-e3c25.appspot.com',
    iosClientId: '71391776673-d5tpdsoli9guvm9st3f43ftbfqpasi35.apps.googleusercontent.com',
    iosBundleId: 'com.app.firebaseIntegrationApp',
  );
}
